### ISSUE TITLE
Don't clutter the artifacts with so many files

### ISSUE THREAD

**Issue by cwbusacker** [saurav0705/check-history-action#51]
I have several tests that run from the same workflow (like 15). I see that this saves each and every job to a different file. This gets ugly really fast and makes it so I can find artifacts that I'm actually interested in.

Perhaps all the data could save to a single json file and update that as more jobs are done?

**Comment by saurav0705** [comment]
@cwbusacker I was saving the data to only one JSON but the challenge with that is there is a race condition happening due to which data was getting overwritten so I changed the approach to individual files. I provided an argument which is `ARTIFACT_RETENTION_DAYS` which makes sure that is deletes the artifacts after some days to prevent cluttering

**Comment by cwbusacker** [comment]
That makes sense. Even with using the artifacts, sometimes it seems like if the very previous run got skipped it's not able to find the artifact and gives me a null commit back.

**Comment by saurav0705** [comment]
actually if you give a rerun the github workflow is unable to find any artifact that is commited on that commit you can only access artifacts that are created by previous commits
I recommend making a setup step on which all the jobs are dependent so this doesn't happen

**Comment by cwbusacker** [comment]
I kind of do that. Maybe I'm missing something.

Here is my yaml:
```
name: "Rikolto tests"

on:
    push:
        branches:
            - main
            - dev
        paths-ignore:
            - ".github/**"
            - "cloud_apis/**"
    pull_request:
        types: [opened, reopened, synchronize]
        branches-ignore: [releases]

jobs:
    changed-files:
        name: Determine changed files
        runs-on: [self-hosted, rikolto]
        outputs:
            fm: ${{ steps.changed-files.outputs.fm_any_modified == 'true' &&  steps.changed-files-between-commits.outputs.fm.shouldRun }}
            tater_spider: ${{ steps.changed-files.outputs.tater_spider_any_modified == 'true' && steps.changed-files-between-commits.outputs.tater_spider.shouldRun }}
            tater_inline: ${{ steps.changed-files.outputs.tater_inline_any_modified == 'true' && steps.changed-files-between-commits.outputs.tater_inline.shouldRun }}
            protein: ${{ steps.changed-files.outputs.protein_any_modified == 'true' && steps.changed-files-between-commits.outputs.protein.shouldRun }}
            siftai: ${{ steps.changed-files.outputs.siftai_any_modified == 'true' && steps.changed-files-between-commits.outputs.siftai.shouldRun }}
            one_sai: ${{ steps.changed-files.outputs.one_sai_any_modified == 'true' && steps.changed-files-between-commits.outputs.one_sai.shouldRun }}
            device_nursery: ${{ steps.changed-files.outputs.device_nursery_any_modified == 'true' && steps.changed-files-between-commits.outputs.device_nursery.shouldRun }}
            maestro_rt: ${{ steps.changed-files.outputs.maestro_rt_any_modified == 'true' && steps.changed-files-between-commits.outputs.maestro_rt.shouldRun }}
            gpio_reporter: ${{ steps.changed-files.outputs.gpio_reporter_any_modified == 'true' && steps.changed-files-between-commits.outputs.gpio_reporter.shouldRun }}
            rsync-sai: ${{ steps.changed-files.outputs.rsync-sai_any_modified == 'true' && steps.changed-files-between-commits.outputs.rsync-sai.shouldRun }}
            cortex_monkey: ${{ steps.changed-files.outputs.cortex_monkey_any_modified == 'true' && steps.changed-files-between-commits.outputs.cortex_monkey.shouldRun }}
        steps:
            - name: Checkout project
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  submodules: recursive
                  token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

            - name: Check Changed Files since Last Successful Run
              id: changed-files-between-commits
              uses: saurav0705/check-history-action@v1.2.0
              with:
                  GIT_TOKEN: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}
                  KEYS: |
                    - key: fm
                      pattern:
                        - fm_hub/!(changelogs/*.json)
                        - fm_hub_no_hardware/!(changelogs/*.json)
                        - fm_sai/!(changelogs/*.json)
                        - siftai/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - gsail-ui/!(changelogs/*.json)
                        - cpp/modules/beagle_lib/!(changelogs/*.json)
                        - cpp/modules/camera/!(changelogs/*.json)
                        - cpp/modules/camera_econ/!(changelogs/*.json)
                        - cpp/modules/camera_fake/!(changelogs/*.json)
                        - cpp/modules/camera_flycap/!(changelogs/*.json)
                        - cpp/modules/camera_pylon/!(changelogs/*.json)
                        - cpp/modules/comm_service/!(changelogs/*.json)
                        - cpp/modules/cpython/!(changelogs/*.json)
                        - cpp/modules/crash/!(changelogs/*.json)
                        - cpp/modules/error/!(changelogs/*.json)
                        - cpp/modules/fastbase64/!(changelogs/*.json)
                        - cpp/modules/gsail/!(changelogs/*.json)
                        - cpp/modules/model/!(changelogs/*.json)
                        - cpp/modules/model_util/!(changelogs/*.json)
                        - cpp/modules/nlohmann/!(changelogs/*.json)
                        - cpp/modules/object_tracking/!(changelogs/*.json)
                        - cpp/modules/serial/!(changelogs/*.json)
                        - cpp/modules/siftai/!(changelogs/*.json)
                        - cpp/modules/svw_logger/!(changelogs/*.json)
                        - cpp/modules/svw_settings/!(changelogs/*.json)
                        - cpp/modules/sync/!(changelogs/*.json)
                        - cpp/modules/sync_queue/!(changelogs/*.json)
                        - cpp/modules/tar/!(changelogs/*.json)
                        - cpp/scons_helpers/!(changelogs/*.json)
                        - gpio_reporter/!(changelogs/*.json)
                        - monogodb/!(changelogs/*.json)

                    - key: tater_spider
                      pattern:
                        - camera-forwarding-sai/!(changelogs/*.json)
                        - tater_spider_sai/!(changelogs/*.json)
                        - fake_spider_robot/!(changelogs/*.json)
                        - siftai/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - gsail-ui/!(changelogs/*.json)
                        - cpp/modules/camera/!(changelogs/*.json)
                        - cpp/modules/camera_econ/!(changelogs/*.json)
                        - cpp/modules/camera_fake/!(changelogs/*.json)
                        - cpp/modules/camera_flycap/!(changelogs/*.json)
                        - cpp/modules/camera_pylon/!(changelogs/*.json)
                        - cpp/modules/comm_service/!(changelogs/*.json)
                        - cpp/modules/cpython/!(changelogs/*.json)
                        - cpp/modules/crash/!(changelogs/*.json)
                        - cpp/modules/error/!(changelogs/*.json)
                        - cpp/modules/fastbase64/!(changelogs/*.json)
                        - cpp/modules/gsail/!(changelogs/*.json)
                        - cpp/modules/model/!(changelogs/*.json)
                        - cpp/modules/model_util/!(changelogs/*.json)
                        - cpp/modules/nlohmann/!(changelogs/*.json)
                        - cpp/modules/object_tracking/!(changelogs/*.json)
                        - cpp/modules/serial/!(changelogs/*.json)
                        - cpp/modules/siftai/!(changelogs/*.json)
                        - cpp/modules/svw_logger/!(changelogs/*.json)
                        - cpp/modules/svw_settings/!(changelogs/*.json)
                        - cpp/modules/sync/!(changelogs/*.json)
                        - cpp/modules/sync_queue/!(changelogs/*.json)
                        - cpp/modules/tar/!(changelogs/*.json)
                        - cpp/modules/tater/!(changelogs/*.json)
                        - cpp/scons_helpers/!(changelogs/*.json)

                    - key: tater_inline
                      pattern:
                        - tater_hub/!(changelogs/*.json)
                        - tater_sai/!(changelogs/*.json)
                        - siftai/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - gsail-ui/!(changelogs/*.json)
                        - cpp/modules/beagle_lib/!(changelogs/*.json)
                        - cpp/modules/camera/!(changelogs/*.json)
                        - cpp/modules/camera_econ/!(changelogs/*.json)
                        - cpp/modules/camera_fake/!(changelogs/*.json)
                        - cpp/modules/camera_flycap/!(changelogs/*.json)
                        - cpp/modules/camera_pylon/!(changelogs/*.json)
                        - cpp/modules/comm_service/!(changelogs/*.json)
                        - cpp/modules/cpython/!(changelogs/*.json)
                        - cpp/modules/crash/!(changelogs/*.json)
                        - cpp/modules/error/!(changelogs/*.json)
                        - cpp/modules/fastbase64/!(changelogs/*.json)
                        - cpp/modules/gsail/!(changelogs/*.json)
                        - cpp/modules/model/!(changelogs/*.json)
                        - cpp/modules/model_util/!(changelogs/*.json)
                        - cpp/modules/nlohmann/!(changelogs/*.json)
                        - cpp/modules/object_tracking/!(changelogs/*.json)
                        - cpp/modules/serial/!(changelogs/*.json)
                        - cpp/modules/siftai/!(changelogs/*.json)
                        - cpp/modules/svw_logger/!(changelogs/*.json)
                        - cpp/modules/svw_settings/!(changelogs/*.json)
                        - cpp/modules/sync/!(changelogs/*.json)
                        - cpp/modules/sync_queue/!(changelogs/*.json)
                        - cpp/modules/tar/!(changelogs/*.json)
                        - cpp/modules/tater/!(changelogs/*.json)
                        - cpp/scons_helpers/!(changelogs/*.json)
                        - gpio_reporter/!(changelogs/*.json)
                        - monogodb/!(changelogs/*.json)

                    - key: protein
                      pattern:
                        - protein_sai/!(changelogs/*.json)
                        - siftai/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - gsail-ui/!(changelogs/*.json)
                        - cpp/modules/camera/!(changelogs/*.json)
                        - cpp/modules/camera_econ/!(changelogs/*.json)
                        - cpp/modules/camera_fake/!(changelogs/*.json)
                        - cpp/modules/camera_flycap/!(changelogs/*.json)
                        - cpp/modules/camera_pylon/!(changelogs/*.json)
                        - cpp/modules/comm_service/!(changelogs/*.json)
                        - cpp/modules/cpython/!(changelogs/*.json)
                        - cpp/modules/crash/!(changelogs/*.json)
                        - cpp/modules/error/!(changelogs/*.json)
                        - cpp/modules/fastbase64/!(changelogs/*.json)
                        - cpp/modules/gsail/!(changelogs/*.json)
                        - cpp/modules/model/!(changelogs/*.json)
                        - cpp/modules/model_util/!(changelogs/*.json)
                        - cpp/modules/nlohmann/!(changelogs/*.json)
                        - cpp/modules/object_tracking/!(changelogs/*.json)
                        - cpp/modules/serial/!(changelogs/*.json)
                        - cpp/modules/siftai/!(changelogs/*.json)
                        - cpp/modules/svw_logger/!(changelogs/*.json)
                        - cpp/modules/svw_settings/!(changelogs/*.json)
                        - cpp/modules/sync/!(changelogs/*.json)
                        - cpp/modules/sync_queue/!(changelogs/*.json)
                        - cpp/modules/tar/!(changelogs/*.json)
                        - cpp/scons_helpers/!(changelogs/*.json)
                      
                    - key: siftai
                      pattern:
                        - siftai/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - gsail-ui/!(changelogs/*.json)
                        - cpp/modules/analyst/!(changelogs/*.json)
                        - cpp/modules/camera/!(changelogs/*.json)
                        - cpp/modules/camera_econ/!(changelogs/*.json)
                        - cpp/modules/camera_fake/!(changelogs/*.json)
                        - cpp/modules/camera_flycap/!(changelogs/*.json)
                        - cpp/modules/camera_pylon/!(changelogs/*.json)
                        - cpp/modules/cipster/!(changelogs/*.json)
                        - cpp/modules/comm_service/!(changelogs/*.json)
                        - cpp/modules/cpython/!(changelogs/*.json)
                        - cpp/modules/crash/!(changelogs/*.json)
                        - cpp/modules/eco_features/!(changelogs/*.json)
                        - cpp/modules/error/!(changelogs/*.json)
                        - cpp/modules/fastbase64/!(changelogs/*.json)
                        - cpp/modules/gsail/!(changelogs/*.json)
                        - cpp/modules/model/!(changelogs/*.json)
                        - cpp/modules/model_util/!(changelogs/*.json)
                        - cpp/modules/nlohmann/!(changelogs/*.json)
                        - cpp/modules/object_tracking/!(changelogs/*.json)
                        - cpp/modules/serial/!(changelogs/*.json)
                        - cpp/modules/siftai/!(changelogs/*.json)
                        - cpp/modules/svw_logger/!(changelogs/*.json)
                        - cpp/modules/svw_settings/!(changelogs/*.json)
                        - cpp/modules/sync/!(changelogs/*.json)
                        - cpp/modules/sync_queue/!(changelogs/*.json)
                        - cpp/modules/tar/!(changelogs/*.json)
                        - cpp/modules/tater/!(changelogs/*.json)
                        - cpp/scons_helpers/!(changelogs/*.json)
                      
                    - key: one_sai
                      pattern:
                        - one_sai/!(changelogs/*.json)
                        - siftai/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - gsail-ui/!(changelogs/*.json)
                        - cpp/modules/analyst/!(changelogs/*.json)
                        - cpp/modules/camera/!(changelogs/*.json)
                        - cpp/modules/camera_econ/!(changelogs/*.json)
                        - cpp/modules/camera_fake/!(changelogs/*.json)
                        - cpp/modules/camera_flycap/!(changelogs/*.json)
                        - cpp/modules/camera_pylon/!(changelogs/*.json)
                        - cpp/modules/cipster/!(changelogs/*.json)
                        - cpp/modules/comm_service/!(changelogs/*.json)
                        - cpp/modules/cpython/!(changelogs/*.json)
                        - cpp/modules/crash/!(changelogs/*.json)
                        - cpp/modules/eco_features/!(changelogs/*.json)
                        - cpp/modules/error/!(changelogs/*.json)
                        - cpp/modules/fastbase64/!(changelogs/*.json)
                        - cpp/modules/gsail/!(changelogs/*.json)
                        - cpp/modules/model/!(changelogs/*.json)
                        - cpp/modules/model_util/!(changelogs/*.json)
                        - cpp/modules/nlohmann/!(changelogs/*.json)
                        - cpp/modules/object_tracking/!(changelogs/*.json)
                        - cpp/modules/serial/!(changelogs/*.json)
                        - cpp/modules/siftai/!(changelogs/*.json)
                        - cpp/modules/svw_logger/!(changelogs/*.json)
                        - cpp/modules/svw_settings/!(changelogs/*.json)
                        - cpp/modules/sync/!(changelogs/*.json)
                        - cpp/modules/sync_queue/!(changelogs/*.json)
                        - cpp/modules/tar/!(changelogs/*.json)
                        - cpp/modules/tater/!(changelogs/*.json)
                        - cpp/scons_helpers/!(changelogs/*.json)
                      
                    - key: device_nursery
                      pattern:
                        - gsail-go/!(changelogs/*.json)
                        - gsail-ui/!(changelogs/*.json)
                        - device_nursery/!(changelogs/*.json)
                      
                    - key: maestro_rt
                      pattern:
                        - maestro_rt/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - cpp/modules/beagle_lib/!(changelogs/*.json)

                    - key: gpio_reporter
                      pattern:
                        - gpio_reporter/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - cpp/modules/beagle_lib/!(changelogs/*.json)
                        - maestro_rt/server/!(changelogs/*.json)

                    - key: rsync-sai
                      pattern:
                        - gsail-go/!(changelogs/*.json)
                        - rsync-sai/!(changelogs/*.json)

                    - key: cortex_monkey
                      pattern:
                        - cortex_monkey/!(changelogs/*.json)
                        - gsail-go/!(changelogs/*.json)
                        - maestro_rt/server/!(changelogs/*.json)
            - name: Check Changes Files since PR base
              id: changed-files
              uses: tj-actions/changed-files@v37
              with:
                  files_yaml: |
                      fm:
                        - fm_hub/**
                        - fm_hub_no_hardware/**
                        - fm_sai/**
                        - siftai/**
                        - gsail-go/**
                        - gsail-ui/**
                        - cpp/modules/beagle_lib/**
                        - cpp/modules/camera/**
                        - cpp/modules/camera_econ/**
                        - cpp/modules/camera_fake/**
                        - cpp/modules/camera_flycap/**
                        - cpp/modules/camera_pylon/**
                        - cpp/modules/comm_service/**
                        - cpp/modules/cpython/**
                        - cpp/modules/crash/**
                        - cpp/modules/error/**
                        - cpp/modules/fastbase64/**
                        - cpp/modules/gsail/**
                        - cpp/modules/model/**
                        - cpp/modules/model_util/**
                        - cpp/modules/nlohmann/**
                        - cpp/modules/object_tracking/**
                        - cpp/modules/serial/**
                        - cpp/modules/siftai/**
                        - cpp/modules/svw_logger/**
                        - cpp/modules/svw_settings/**
                        - cpp/modules/sync/**
                        - cpp/modules/sync_queue/**
                        - cpp/modules/tar/**
                        - cpp/scons_helpers/**
                        - gpio_reporter/**
                        - monogodb/**
                        - !**/changelogs/*.json
                      tater_spider:
                        - camera-forwarding-sai/**
                        - tater_spider_sai/**
                        - fake_spider_robot/**
                        - siftai/**
                        - gsail-go/**
                        - gsail-ui/**
                        - cpp/modules/camera/**
                        - cpp/modules/camera_econ/**
                        - cpp/modules/camera_fake/**
                        - cpp/modules/camera_flycap/**
                        - cpp/modules/camera_pylon/**
                        - cpp/modules/comm_service/**
                        - cpp/modules/cpython/**
                        - cpp/modules/crash/**
                        - cpp/modules/error/**
                        - cpp/modules/fastbase64/**
                        - cpp/modules/gsail/**
                        - cpp/modules/model/**
                        - cpp/modules/model_util/**
                        - cpp/modules/nlohmann/**
                        - cpp/modules/object_tracking/**
                        - cpp/modules/serial/**
                        - cpp/modules/siftai/**
                        - cpp/modules/svw_logger/**
                        - cpp/modules/svw_settings/**
                        - cpp/modules/sync/**
                        - cpp/modules/sync_queue/**
                        - cpp/modules/tar/**
                        - cpp/modules/tater/**
                        - cpp/scons_helpers/**
                        - !**/changelogs/*.json
                      tater_inline:
                        - tater_hub/**
                        - tater_sai/**
                        - siftai/**
                        - gsail-go/**
                        - gsail-ui/**
                        - cpp/modules/beagle_lib/**
                        - cpp/modules/camera/**
                        - cpp/modules/camera_econ/**
                        - cpp/modules/camera_fake/**
                        - cpp/modules/camera_flycap/**
                        - cpp/modules/camera_pylon/**
                        - cpp/modules/comm_service/**
                        - cpp/modules/cpython/**
                        - cpp/modules/crash/**
                        - cpp/modules/error/**
                        - cpp/modules/fastbase64/**
                        - cpp/modules/gsail/**
                        - cpp/modules/model/**
                        - cpp/modules/model_util/**
                        - cpp/modules/nlohmann/**
                        - cpp/modules/object_tracking/**
                        - cpp/modules/serial/**
                        - cpp/modules/siftai/**
                        - cpp/modules/svw_logger/**
                        - cpp/modules/svw_settings/**
                        - cpp/modules/sync/**
                        - cpp/modules/sync_queue/**
                        - cpp/modules/tar/**
                        - cpp/modules/tater/**
                        - cpp/scons_helpers/**
                        - gpio_reporter/**
                        - monogodb/**
                        - !**/changelogs/*.json
                      protein:
                        - protein_sai/**
                        - siftai/**
                        - gsail-go/**
                        - gsail-ui/**
                        - cpp/modules/camera/**
                        - cpp/modules/camera_econ/**
                        - cpp/modules/camera_fake/**
                        - cpp/modules/camera_flycap/**
                        - cpp/modules/camera_pylon/**
                        - cpp/modules/comm_service/**
                        - cpp/modules/cpython/**
                        - cpp/modules/crash/**
                        - cpp/modules/error/**
                        - cpp/modules/fastbase64/**
                        - cpp/modules/gsail/**
                        - cpp/modules/model/**
                        - cpp/modules/model_util/**
                        - cpp/modules/nlohmann/**
                        - cpp/modules/object_tracking/**
                        - cpp/modules/serial/**
                        - cpp/modules/siftai/**
                        - cpp/modules/svw_logger/**
                        - cpp/modules/svw_settings/**
                        - cpp/modules/sync/**
                        - cpp/modules/sync_queue/**
                        - cpp/modules/tar/**
                        - cpp/scons_helpers/**
                        - !**/changelogs/*.json
                      siftai:
                        - siftai/**
                        - gsail-go/**
                        - gsail-ui/**
                        - cpp/modules/analyst/**
                        - cpp/modules/camera/**
                        - cpp/modules/camera_econ/**
                        - cpp/modules/camera_fake/**
                        - cpp/modules/camera_flycap/**
                        - cpp/modules/camera_pylon/**
                        - cpp/modules/cipster/**
                        - cpp/modules/comm_service/**
                        - cpp/modules/cpython/**
                        - cpp/modules/crash/**
                        - cpp/modules/eco_features/**
                        - cpp/modules/error/**
                        - cpp/modules/fastbase64/**
                        - cpp/modules/gsail/**
                        - cpp/modules/model/**
                        - cpp/modules/model_util/**
                        - cpp/modules/nlohmann/**
                        - cpp/modules/object_tracking/**
                        - cpp/modules/serial/**
                        - cpp/modules/siftai/**
                        - cpp/modules/stem_features/**
                        - cpp/modules/svw_classifier/**
                        - cpp/modules/svw_logger/**
                        - cpp/modules/svw_settings/**
                        - cpp/modules/sync/**
                        - cpp/modules/sync_queue/**
                        - cpp/modules/tar/**
                        - cpp/modules/tater/**
                        - cpp/scons_helpers/**
                        - !**/changelogs/*.json
                      one_sai:
                        - one_sai/**
                        - siftai/**
                        - gsail-go/**
                        - gsail-ui/**
                        - cpp/modules/analyst/**
                        - cpp/modules/camera/**
                        - cpp/modules/camera_econ/**
                        - cpp/modules/camera_fake/**
                        - cpp/modules/camera_flycap/**
                        - cpp/modules/camera_pylon/**
                        - cpp/modules/cipster/**
                        - cpp/modules/comm_service/**
                        - cpp/modules/cpython/**
                        - cpp/modules/crash/**
                        - cpp/modules/eco_features/**
                        - cpp/modules/error/**
                        - cpp/modules/fastbase64/**
                        - cpp/modules/gsail/**
                        - cpp/modules/model/**
                        - cpp/modules/model_util/**
                        - cpp/modules/nlohmann/**
                        - cpp/modules/object_tracking/**
                        - cpp/modules/serial/**
                        - cpp/modules/siftai/**
                        - cpp/modules/stem_features/**
                        - cpp/modules/svw_classifier/**
                        - cpp/modules/svw_logger/**
                        - cpp/modules/svw_settings/**
                        - cpp/modules/sync/**
                        - cpp/modules/sync_queue/**
                        - cpp/modules/tar/**
                        - cpp/modules/tater/**
                        - cpp/scons_helpers/**
                        - !**/changelogs/*.json
                      device_nursery:
                        - gsail-go/**
                        - gsail-ui/**
                        - device_nursery/**
                        - !**/changelogs/*.json
                      maestro_rt:
                        - maestro_rt/**
                        - gsail-go/**
                        - cpp/modules/beagle_lib/**
                        - !**/changelogs/*.json
                      gpio_reporter:
                        - gpio_reporter/**
                        - gsail-go/**
                        - cpp/modules/beagle_lib/**
                        - maestro_rt/server/**
                        - !**/changelogs/*.json
                      cloud_api:
                        - cloud_apis/**
                        - !**/changelogs/*.json
                      rsync-sai:
                        - gsail-go/**
                        - rsync-sai/**
                        - !**/changelogs/*.json
                      cortex_monkey:
                        - cortex_monkey/**
                        - gsail-go/**
                        - maestro_rt/server/**
                        - !**/changelogs/*.json

    fm_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: fm/suite.yml
            skip: ${{ needs.changed-files.outputs.fm == 'false' }}
            key: fm
        secrets:
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    tater_spider_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: tater_spider/basic.yml
            skip: ${{ needs.changed-files.outputs.tater_spider == 'false' }}
            key: tater_spider
        secrets:
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    tater_inline_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: tater/inline.suite.yml
            skip: ${{ needs.changed-files.outputs.tater_inline == 'false' }}
            key: tater_inline
        secrets:
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    protein_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: protein/single.yml
            skip: ${{ needs.changed-files.outputs.protein == 'false' }}
            key: protein
        secrets:
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    siftai_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: siftai/basic.yml
            skip: ${{ needs.changed-files.outputs.siftai == 'false' }}
            key: siftai
        secrets:
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    one_sai_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: one_sai/build_only.yml
            skip: ${{ needs.changed-files.outputs.one_sai == 'false' }}
            key: one_sai
        secrets:
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    device_nursery_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: device_nursery/basic.yml
            skip: ${{ needs.changed-files.outputs.device_nursery == 'false' }}
            key: device_nursery
        secrets:
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    maestro_rt_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: maestro_rt/suite.yml
            skip: ${{ needs.changed-files.outputs.maestro_rt == 'false' }}
            key: maestro_rt
        secrets:            
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    gpio_reporter_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: gpio_reporter/suite.yml
            skip: ${{ needs.changed-files.outputs.gpio_reporter == 'false' }}
            key: gpio_reporter 
        secrets:                 
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    rsync-sai_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: rsync-sai/build_only.yml
            skip: ${{ needs.changed-files.outputs.rsync-sai == 'false' }}
            key: rsync-sai  
        secrets:                
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}

    cortex_monkey_test:
        needs: changed-files
        uses: Smart-Vision-Works/github_workflows/.github/workflows/rikolto.yml@better-changed-files-checking
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}
            test_file: cortex_monkey/build_only.yml
            skip: ${{ needs.changed-files.outputs.cortex_monkey == 'false' }}
            key: cortex_monkey
        secrets:
            token: ${{ secrets.RELEASENOTESGENERATOR_GITHUBTOKEN }}
```
